# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: cuukenn的博客
subtitle: '891842749@qq.com'
description: '山止川行，风禾尽起'
keywords: ''
author: changgg
language: zh-CN
timezone: 'Etc/GMT+8'
# URL
url: https://cuukenn.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true
# Extensions
theme: next
plugins: hexo-generate-feed
# Deployment
deploy:
  type: 'git'
  repo: 'git@github.com:cuukenn/cuukenn.github.io.git'
  branch: 'master'
# hexo word counter
symbols_count_time:
  total_symbols: true
  total_time: true
  symbols: false
  time: false
  awl: 4
  wpm: 275
# hexo-generator-searchdb
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
